import type { LucideIcon } from 'lucide-react'
import {
  Search,
  Palette,
  BookOpen,
  BookMarked,
  Download,
  LayoutDashboard,
  Images,
  FolderTree,
  Rss,
  Settings,
  Users,
  Clock,
  PackageOpen,
  FolderInput,
  Key,
  Puzzle,
  Tags,
  Trash2,
  CalendarClock,
  ScanSearch,
  ScrollText,
  ShieldCheck,
  Globe,
  Activity,
  ListTodo,
} from 'lucide-react'
import type { UserRole } from '@/lib/types'

export interface PageDef {
  href: string
  labelKey: string
  descKey?: string
  icon: LucideIcon
  /** Appears in the BottomTabBar candidate pool */
  nav: boolean
  /** Appears in the Dashboard Quick Links grid */
  dashboard: boolean
  /** Appears in sidebar navigation */
  sidebar: boolean
  /** Minimum role required to see this page */
  minRole?: UserRole
}

export function hasRole(userRole: string | undefined, minRole: UserRole): boolean {
  const ROLE_LEVEL: Record<string, number> = { admin: 3, member: 2, viewer: 1 }
  return (ROLE_LEVEL[userRole || 'viewer'] ?? 0) >= ROLE_LEVEL[minRole]
}

export const PAGE_REGISTRY: PageDef[] = [
  {
    href: '/',
    labelKey: 'nav.dashboard',
    descKey: undefined,
    icon: LayoutDashboard,
    nav: true,
    dashboard: false,
    sidebar: true,
    minRole: 'viewer',
  },
  {
    href: '/e-hentai',
    labelKey: 'nav.ehentai',
    descKey: 'dashboard.quickLinks.ehentaiDesc',
    icon: Search,
    nav: true,
    dashboard: true,
    sidebar: true,
    minRole: 'viewer',
  },
  {
    href: '/pixiv',
    labelKey: 'nav.pixiv',
    descKey: 'dashboard.quickLinks.pixivDesc',
    icon: Palette,
    nav: true,
    dashboard: true,
    sidebar: true,
    minRole: 'viewer',
  },
  {
    href: '/library',
    labelKey: 'nav.library',
    descKey: 'dashboard.quickLinks.libraryDesc',
    icon: BookOpen,
    nav: true,
    dashboard: true,
    sidebar: true,
    minRole: 'viewer',
  },
  {
    href: '/reading-list',
    labelKey: 'nav.readingList',
    descKey: 'dashboard.quickLinks.readingListDesc',
    icon: BookMarked,
    nav: true,
    dashboard: true,
    sidebar: true,
    minRole: 'viewer',
  },
  {
    href: '/trash',
    labelKey: 'nav.trash',
    descKey: 'dashboard.quickLinks.trashDesc',
    icon: Trash2,
    nav: false,
    dashboard: true,
    sidebar: true,
    minRole: 'viewer',
  },
  {
    href: '/images',
    labelKey: 'nav.images',
    descKey: 'dashboard.quickLinks.imagesDesc',
    icon: Images,
    nav: true,
    dashboard: true,
    sidebar: true,
    minRole: 'viewer',
  },
  {
    href: '/explorer',
    labelKey: 'nav.explorer',
    descKey: 'dashboard.quickLinks.explorerDesc',
    icon: FolderTree,
    nav: true,
    dashboard: true,
    sidebar: true,
    minRole: 'viewer',
  },
  {
    href: '/artists',
    labelKey: 'nav.artists',
    descKey: 'dashboard.quickLinks.artistsDesc',
    icon: Users,
    nav: false,
    dashboard: true,
    sidebar: true,
    minRole: 'viewer',
  },
  {
    href: '/subscriptions',
    labelKey: 'nav.subscriptions',
    descKey: 'dashboard.quickLinks.subscriptionsDesc',
    icon: Rss,
    nav: true,
    dashboard: true,
    sidebar: true,
    minRole: 'member',
  },
  {
    href: '/history',
    labelKey: 'nav.history',
    descKey: 'dashboard.quickLinks.historyDesc',
    icon: Clock,
    nav: false,
    dashboard: true,
    sidebar: true,
    minRole: 'viewer',
  },
  {
    href: '/queue',
    labelKey: 'nav.queue',
    descKey: 'dashboard.quickLinks.queueDesc',
    icon: Download,
    nav: true,
    dashboard: true,
    sidebar: true,
    minRole: 'member',
  },
  {
    href: '/tags',
    labelKey: 'nav.tags',
    descKey: 'dashboard.quickLinks.tagsDesc',
    icon: Tags,
    nav: false,
    dashboard: true,
    sidebar: true,
    minRole: 'viewer',
  },
  {
    href: '/export',
    labelKey: 'nav.export',
    descKey: 'dashboard.quickLinks.exportDesc',
    icon: PackageOpen,
    nav: false,
    dashboard: true,
    sidebar: true,
    minRole: 'member',
  },
  {
    href: '/import',
    labelKey: 'nav.import',
    descKey: 'dashboard.quickLinks.importDesc',
    icon: FolderInput,
    nav: true,
    dashboard: true,
    sidebar: true,
    minRole: 'member',
  },
  {
    href: '/scheduled-tasks',
    labelKey: 'nav.scheduledTasks',
    descKey: 'dashboard.quickLinks.scheduledTasksDesc',
    icon: CalendarClock,
    nav: false,
    dashboard: true,
    sidebar: true,
    minRole: 'admin',
  },
  {
    href: '/dedup',
    labelKey: 'nav.dedup',
    descKey: 'dashboard.quickLinks.dedupDesc',
    icon: ScanSearch,
    nav: false,
    dashboard: true,
    sidebar: true,
    minRole: 'admin',
  },
  {
    href: '/credentials',
    labelKey: 'nav.credentials',
    descKey: 'dashboard.quickLinks.credentialsDesc',
    icon: Key,
    nav: false,
    dashboard: true,
    sidebar: true,
    minRole: 'admin',
  },
  {
    href: '/plugins',
    labelKey: 'nav.plugins',
    descKey: 'dashboard.quickLinks.pluginsDesc',
    icon: Puzzle,
    nav: false,
    dashboard: true,
    sidebar: true,
    minRole: 'admin',
  },
  {
    href: '/settings',
    labelKey: 'nav.settings',
    descKey: 'dashboard.quickLinks.settingsDesc',
    icon: Settings,
    nav: true,
    dashboard: true,
    sidebar: false,
  },
  {
    href: '/logs',
    labelKey: 'nav.logs',
    icon: ScrollText,
    nav: false,
    dashboard: false,
    sidebar: true,
    minRole: 'admin',
  },
  {
    href: '/admin/users',
    labelKey: 'nav.users',
    icon: ShieldCheck,
    nav: false,
    dashboard: false,
    sidebar: true,
    minRole: 'admin',
  },
  {
    href: '/admin/sites',
    labelKey: 'nav.siteConfig',
    icon: Globe,
    nav: false,
    dashboard: false,
    sidebar: true,
    minRole: 'admin',
  },
  {
    href: '/admin/dashboard',
    labelKey: 'nav.downloadDashboard',
    icon: Activity,
    nav: false,
    dashboard: false,
    sidebar: true,
    minRole: 'admin',
  },
  {
    href: '/admin/queue',
    labelKey: 'nav.queueDashboard',
    icon: ListTodo,
    nav: false,
    dashboard: false,
    sidebar: true,
    minRole: 'admin' as UserRole,
  },
]
